# Generated by Django 4.2.20 on 2025-05-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Estudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Fotografo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especialidade", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SessaoFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("tipo", models.CharField(max_length=50)),
                ("duracao", models.PositiveIntegerField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.cliente",
                    ),
                ),
                (
                    "estudio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.estudio",
                    ),
                ),
                (
                    "fotografo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.fotografo",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="curso",
            name="campus",
        ),
        migrations.DeleteModel(
            name="TipoSolicitacao",
        ),
        migrations.DeleteModel(
            name="Campus",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
    ]
