# Generated by Django 4.2.20 on 2025-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0002_cliente_estudio_fotografo_sessaofoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessaofoto",
            name="finalizado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessaofoto",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=300, max_digits=7),
            preserve_default=False,
        ),
    ]
