# Generated by Django 5.2.1 on 2025-05-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_cliente_email_alter_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
